### ISSUE TITLE
راهنما

### ISSUE THREAD

**Issue by Sina157** [DexterFstone/godot-poolakey#1]
راهنما یا داکیومنت برای استفاده از پلایگین

**Comment by Sina157** [comment]
https://github.com/DexterFstone/GodotPoolakeyPluginDocument

**Comment by DexterFstone** [comment]
> https://github.com/DexterFstone/GodotPoolakeyPluginDocument

تمامی متد ها یکی هست بجز `start_setup` که شده  `connect_to_cafebazaar`

**Comment by Sina157** [comment]
کلاس Payment وجود ندارد
![Capture](https://github.com/user-attachments/assets/f9845219-813a-4a71-9eab-f1d37aa4a507)

**Comment by DexterFstone** [comment]
> کلاس Payment وجود ندارد ![Capture](https://private-user-images.githubusercontent.com/95890589/395876904-f9845219-813a-4a71-9eab-f1d37aa4a507.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODQzMTQsIm5iZiI6MTczNDI4NDAxNCwicGF0aCI6Ii85NTg5MDU4OS8zOTU4NzY5MDQtZjk4NDUyMTktODEzYS00YTcxLTllYWItZjFkMzdhYTRhNTA3LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDE3MzMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMjNhMjhmMWZhZjY4NjBkMTRmOTFjMmQ5MjExMTliNzI2MDI1MmRjNTlmMDJjNWZhOTBlMWNiMzU5ZmY3NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vPzCX6HQr71QTeajzCYJc3lq51yG4pQFIv2C46dKQjM)

اسم کلاس `poolakey` هستش

**Comment by Sina157** [comment]
if not _has_singleton(): return 
این خط کد تابع رو return میکنه و plugin کار نمیکنه آیا لازم کار دیگه ای انجام بدم؟ ورژن 4.3

**Comment by DexterFstone** [comment]
> if not _has_singleton(): return این خط کد تابع رو return میکنه و plugin کار نمیکنه آیا لازم کار دیگه ای انجام بدم؟ ورژن 4.3

نیازی ب استفاده از این ندارید، برای چی میخواین از این تابع استفاده کنید ؟

**Comment by Sina157** [comment]
این خط کد همان کدی است در تابع connect_to_cafebazaar وجود دارد و باعث می شود این تابع کاری انجام ندهد
خط 34 poolakey.gd

_plugin = _get_singleton() 
اینم null میشه اگه کامنتش کنم

**Comment by DexterFstone** [comment]
> این خط کد همان کدی است در تابع connect_to_cafebazaar وجود دارد و باعث می شود این تابع کاری انجام ندهد خط 34 poolakey.gd
> 
> _plugin = _get_singleton() اینم null میشه اگه کامنتش کنم

بله داخلی استفاده شده و مشکلی هم نداره الان شما دارید خطایی چیزی دریافت میکنید؟

**Comment by Sina157** [comment]
خطایی نمی‌دهد  همونطور که اشاره کردم تابع اصلی کار نمی کند.
آیا فقط نصب کردن پلاگین کافی است؟ چطور باید تست کنیم؟

**Comment by DexterFstone** [comment]
> خطایی نمی‌دهد همونطور که اشاره کردم تابع اصلی کار نمی کند. آیا فقط نصب کردن پلاگین کافی است؟ چطور باید تست کنیم؟

باید تیک پلاگین هم داخل تنظیمات پروژه فعال کنید

**Comment by Sina157** [comment]
این مورد هم انجام دادم
گودو ورژن۴.۳ استفاده میکنم شاید دلیلش این باشد

**Comment by DexterFstone** [comment]
> این مورد هم انجام دادم گودو ورژن۴.۳ استفاده میکنم شاید دلیلش این باشد

خب منم با این نسخه تست کردم مشکلی نبوده

**Comment by Sina157** [comment]
فهمیدم مشکل از کجاست build.gradle رو هم باید تغییر میدادم فقط نصب این پلاگین کافی نیست

**Comment by DexterFstone** [comment]
> فهمیدم مشکل از کجاست build.gradle رو هم باید تغییر میدادم فقط نصب این پلاگین کافی نیست

والا طبق چیزی ک من اطلاع دارم چنین چیزی نیست ولی خب تغییر را ارسال کنید تا بررسی کنم و مطلع بشم

**Comment by Sina157** [comment]
به مستندات کافه بازار مراجعه کردم اینجا گفته چیکار کنیم
https://developers.cafebazaar.ir/fa/guidelines/in-app-billing/implementation/kotlin#import-library

**Comment by DexterFstone** [comment]
> به مستندات کافه بازار مراجعه کردم اینجا گفته چیکار کنیم https://developers.cafebazaar.ir/fa/guidelines/in-app-billing/implementation/kotlin#import-library

این موارد توسط `plugin.gd` پیکر بندی میشن

**Comment by Sina157** [comment]
> > به مستندات کافه بازار مراجعه کردم اینجا گفته چیکار کنیم https://developers.cafebazaar.ir/fa/guidelines/in-app-billing/implementation/kotlin#import-library
> 
> این موارد توسط `plugin.gd` پیکر بندی میشن

برای من که کار نکرد 
اصلا این اسکریپت اجرا نمیشه

**Comment by DexterFstone** [comment]
> > > به مستندات کافه بازار مراجعه کردم اینجا گفته چیکار کنیم https://developers.cafebazaar.ir/fa/guidelines/in-app-billing/implementation/kotlin#import-library
> > 
> > 
> > این موارد توسط `plugin.gd` پیکر بندی میشن
> 
> برای من که کار نکرد اصلا این اسکریپت اجرا نمیشه

مگه تیک پلاگین نزدید؟ داخل تنظیمات پروژه

**Comment by Sina157** [comment]
![Capture](https://github.com/user-attachments/assets/1df1580d-9d96-498f-b7f9-298405bd4115)
زدم

**Comment by Sina157** [comment]
> ![Capture](https://private-user-images.githubusercontent.com/95890589/397976521-1df1580d-9d96-498f-b7f9-298405bd4115.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjIzNTcsIm5iZiI6MTczNDg2MjA1NywicGF0aCI6Ii85NTg5MDU4OS8zOTc5NzY1MjEtMWRmMTU4MGQtOWQ5Ni00OThmLWI3ZjktMjk4NDA1YmQ0MTE1LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDEwMDczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYWVjMWExMzUyMzFmN2JlY2YzMTMwOWQ5N2M3NjNmOWRmZWY0ZGY4MjBiZmMyZmNmYWFkYzMyYjE4MDc2MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L0F6pDR0rYBseP0XGbMACmWSLVmeIneP3okfnVYDCNk) 

زدم فقط موقع خروجی گرفتن برای اندروید اجرا میشه 
تابع ها درست کار نمی کنن یسری ها اجرا میشن مثل خرید ولی بعضایشون کار نمی کنه ارور میدن مثل 

E 0:00:03:0229   poolakey.gd:155 @ __on_purchased_query_succeed(): Error calling from signal 'purchased_query_succeed' to callable: 'Node(poolakey.gd)::_on_purchased_query_succeed': Cannot convert argument 1 from Array to Array.
  <C++ Source>   core/object/object.cpp:1200 @ emit_signalp()
  <Stack Trace>  poolakey.gd:155 @ __on_purchased_query_succeed()

**Comment by DexterFstone** [comment]
> > ![Capture](https://private-user-images.githubusercontent.com/95890589/397976521-1df1580d-9d96-498f-b7f9-298405bd4115.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjIzNTcsIm5iZiI6MTczNDg2MjA1NywicGF0aCI6Ii85NTg5MDU4OS8zOTc5NzY1MjEtMWRmMTU4MGQtOWQ5Ni00OThmLWI3ZjktMjk4NDA1YmQ0MTE1LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDEwMDczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYWVjMWExMzUyMzFmN2JlY2YzMTMwOWQ5N2M3NjNmOWRmZWY0ZGY4MjBiZmMyZmNmYWFkYzMyYjE4MDc2MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L0F6pDR0rYBseP0XGbMACmWSLVmeIneP3okfnVYDCNk)
> 
> زدم فقط موقع خروجی گرفتن برای اندروید اجرا میشه تابع ها درست کار نمی کنن یسری ها اجرا میشن مثل خرید ولی بعضایشون کار نمی کنه ارور میدن مثل
> 
> E 0:00:03:0229 poolakey.gd:155 @ __on_purchased_query_succeed(): Error calling from signal 'purchased_query_succeed' to callable: 'Node(poolakey.gd)::_on_purchased_query_succeed': Cannot convert argument 1 from Array to Array. <C++ Source> core/object/object.cpp:1200 @ emit_signalp() poolakey.gd:155 @ __on_purchased_query_succeed()

نسخه جدید از بخش ریلیز دریافت کنید رفع شده

**Comment by Sina157** [comment]
![Capture](https://github.com/user-attachments/assets/495e1c4f-04c8-4e1a-a4a8-19f43267dfc5)
این خطا رو داده بعد از نصب نسخه جدید
ارور قبلی هم همچنان هست و متد ها کار نمی کنن

E 0:00:03:0361   poolakey.gd:154 @ __on_purchased_query_succeed(): Error calling from signal 'purchased_query_succeed' to callable: 'Node(poolakey.gd)::_on_purchased_query_succeed': Cannot convert argument 1 from Array to Array.
  <C++ Source>   core/object/object.cpp:1200 @ emit_signalp()
  <Stack Trace>  poolakey.gd:154 @ __on_purchased_query_succeed()


E 0:00:05:0101   poolakey.gd:135 @ __on_purchase_succeed(): Error calling from signal 'purchase_succeed' to callable: 'Node(poolakey.gd)::_on_purchase_succeed': Cannot convert argument 1 from Dictionary to Object.
  <C++ Source>   core/object/object.cpp:1200 @ emit_signalp()
  <Stack Trace>  poolakey.gd:135 @ __on_purchase_succeed()


فکر میکنم اگه توی سیگنال ها پارامتر رو داینامیک کنید مشکل حل بشه

**Comment by DexterFstone** [comment]
> ![Capture](https://private-user-images.githubusercontent.com/95890589/397984747-495e1c4f-04c8-4e1a-a4a8-19f43267dfc5.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzMwODYsIm5iZiI6MTczNDg3Mjc4NiwicGF0aCI6Ii85NTg5MDU4OS8zOTc5ODQ3NDctNDk1ZTFjNGYtMDRjOC00ZTFhLWE0YTgtMTlmNDMyNjdkZmM1LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDEzMDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NzNjMjA0NDBmY2VmOWNiYjk3MGMwN2UxOWMxZDJjZWE4NDkxOWUyY2FjOGZjMGFhNDIyMTgxZTlhYWJmMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qlqhdRg44G7OaYtUYT32Np743pRYL3kmBnHo70FGo_w) این خطا رو داده بعد از نصب نسخه جدید ارور قبلی هم همچنان هست و متد ها کار نمی کنن
> 
> E 0:00:03:0361 poolakey.gd:154 @ __on_purchased_query_succeed(): Error calling from signal 'purchased_query_succeed' to callable: 'Node(poolakey.gd)::_on_purchased_query_succeed': Cannot convert argument 1 from Array to Array. <C++ Source> core/object/object.cpp:1200 @ emit_signalp() poolakey.gd:154 @ __on_purchased_query_succeed()
> 
> E 0:00:05:0101 poolakey.gd:135 @ __on_purchase_succeed(): Error calling from signal 'purchase_succeed' to callable: 'Node(poolakey.gd)::_on_purchase_succeed': Cannot convert argument 1 from Dictionary to Object. <C++ Source> core/object/object.cpp:1200 @ emit_signalp() poolakey.gd:135 @ __on_purchase_succeed()
> 
> فکر میکنم اگه توی سیگنال ها پارامتر رو داینامیک کنید مشکل حل بشه

خط 135 بجای `info` باید `purchase_info` ارسال شود داخل کلاس `poolakey`
